/* tslint:disable */
/* eslint-disable */
/**
 * Shopee API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface GetOrderListResponse
 */
export interface GetOrderListResponse {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponse
     */
    'error'?: number;
    /**
     * 
     * @type {GetOrderListResponseData}
     * @memberof GetOrderListResponse
     */
    'data'?: GetOrderListResponseData;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseData
 */
export interface GetOrderListResponseData {
    /**
     * 
     * @type {Array<GetOrderListResponseDataDetailsList>}
     * @memberof GetOrderListResponseData
     */
    'details_list'?: Array<GetOrderListResponseDataDetailsList>;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseData
     */
    'next_offset'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataDetailsList
 */
export interface GetOrderListResponseDataDetailsList {
    /**
     * 
     * @type {GetOrderListResponseDataStatus}
     * @memberof GetOrderListResponseDataDetailsList
     */
    'status'?: GetOrderListResponseDataStatus;
    /**
     * 
     * @type {GetOrderListResponseDataShipping}
     * @memberof GetOrderListResponseDataDetailsList
     */
    'shipping'?: GetOrderListResponseDataShipping;
    /**
     * 
     * @type {GetOrderListResponseDataInfoCard}
     * @memberof GetOrderListResponseDataDetailsList
     */
    'info_card'?: GetOrderListResponseDataInfoCard;
    /**
     * 
     * @type {Array<GetOrderListResponseDataPrimaryButtons>}
     * @memberof GetOrderListResponseDataDetailsList
     */
    'primary_buttons'?: Array<GetOrderListResponseDataPrimaryButtons>;
    /**
     * 
     * @type {GetOrderListResponseDataGuarantee}
     * @memberof GetOrderListResponseDataDetailsList
     */
    'guarantee'?: GetOrderListResponseDataGuarantee;
    /**
     * 
     * @type {Array<GetOrderListResponseDataPrimaryButtons>}
     * @memberof GetOrderListResponseDataDetailsList
     */
    'secondary_buttons'?: Array<GetOrderListResponseDataPrimaryButtons>;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataDetailsList
     */
    'list_type'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataGuarantee
 */
export interface GetOrderListResponseDataGuarantee {
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataGuarantee
     */
    'learn_more_url'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataGuarantee
     */
    'is_extend_enabled'?: boolean;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCard
 */
export interface GetOrderListResponseDataInfoCard {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCard
     */
    'order_id'?: number;
    /**
     * 
     * @type {Array<GetOrderListResponseDataInfoCardOrderListCards>}
     * @memberof GetOrderListResponseDataInfoCard
     */
    'order_list_cards'?: Array<GetOrderListResponseDataInfoCardOrderListCards>;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCard
     */
    'product_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCard
     */
    'subtotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCard
     */
    'final_total'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardItems
 */
export interface GetOrderListResponseDataInfoCardItems {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'item_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'model_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'shop_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'model_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'image'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'item_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'price_before_discount'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'order_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardItems
     */
    'snapshot_id'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardOrderListCards
 */
export interface GetOrderListResponseDataInfoCardOrderListCards {
    /**
     * 
     * @type {GetOrderListResponseDataInfoCardShopInfo}
     * @memberof GetOrderListResponseDataInfoCardOrderListCards
     */
    'shop_info'?: GetOrderListResponseDataInfoCardShopInfo;
    /**
     * 
     * @type {Array<GetOrderListResponseDataInfoCardItems>}
     * @memberof GetOrderListResponseDataInfoCardOrderListCards
     */
    'items'?: Array<GetOrderListResponseDataInfoCardItems>;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardOrderListCards
     */
    'order_id'?: number;
    /**
     * 
     * @type {Array<GetOrderListResponseDataInfoCardParcelCards>}
     * @memberof GetOrderListResponseDataInfoCardOrderListCards
     */
    'parcel_cards'?: Array<GetOrderListResponseDataInfoCardParcelCards>;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardParcelCards
 */
export interface GetOrderListResponseDataInfoCardParcelCards {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardParcelCards
     */
    'parcel_no'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardParcelCards
     */
    'forder_id'?: string;
    /**
     * 
     * @type {GetOrderListResponseDataInfoCardProductInfo}
     * @memberof GetOrderListResponseDataInfoCardParcelCards
     */
    'product_info'?: GetOrderListResponseDataInfoCardProductInfo;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardProductInfo
 */
export interface GetOrderListResponseDataInfoCardProductInfo {
    /**
     * 
     * @type {Array<GetOrderListResponseDataInfoCardProductInfoItemGroups>}
     * @memberof GetOrderListResponseDataInfoCardProductInfo
     */
    'item_groups'?: Array<GetOrderListResponseDataInfoCardProductInfoItemGroups>;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfo
     */
    'total_num_items'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardProductInfoExtInfo
 */
export interface GetOrderListResponseDataInfoCardProductInfoExtInfo {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoExtInfo
     */
    'add_on_deal_id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataInfoCardProductInfoExtInfo
     */
    'is_add_on_sub_item'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoExtInfo
     */
    'free_return_day'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataInfoCardProductInfoExtInfo
     */
    'is_wholesale'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataInfoCardProductInfoExtInfo
     */
    'is_pre_order'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataInfoCardProductInfoExtInfo
     */
    'is_membership_gift'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataInfoCardProductInfoExtInfo
     */
    'is_free_return'?: boolean;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardProductInfoItemGroups
 */
export interface GetOrderListResponseDataInfoCardProductInfoItemGroups {
    /**
     * 
     * @type {Array<GetOrderListResponseDataInfoCardProductInfoItems>}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItemGroups
     */
    'items'?: Array<GetOrderListResponseDataInfoCardProductInfoItems>;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItemGroups
     */
    'num_items'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardProductInfoItems
 */
export interface GetOrderListResponseDataInfoCardProductInfoItems {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'item_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'model_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'shop_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'model_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'image'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'amount'?: number;
    /**
     * 
     * @type {GetOrderListResponseDataInfoCardProductInfoExtInfo}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'ext_info'?: GetOrderListResponseDataInfoCardProductInfoExtInfo;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'item_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'price_before_discount'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'order_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardProductInfoItems
     */
    'snapshot_id'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataInfoCardShopInfo
 */
export interface GetOrderListResponseDataInfoCardShopInfo {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardShopInfo
     */
    'shop_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardShopInfo
     */
    'shop_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardShopInfo
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardShopInfo
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataInfoCardShopInfo
     */
    'portrait'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataInfoCardShopInfo
     */
    'shop_tag'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataPrimaryButtons
 */
export interface GetOrderListResponseDataPrimaryButtons {
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataPrimaryButtons
     */
    'id'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataShipping
 */
export interface GetOrderListResponseDataShipping {
    /**
     * 
     * @type {GetOrderListResponseDataShippingTrackingInfo}
     * @memberof GetOrderListResponseDataShipping
     */
    'tracking_info'?: GetOrderListResponseDataShippingTrackingInfo;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataShipping
     */
    'is_multi_parcel'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataShipping
     */
    'num_parcels'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataShipping
     */
    'parcel_no'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataShippingTrackingInfo
 */
export interface GetOrderListResponseDataShippingTrackingInfo {
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataShippingTrackingInfo
     */
    'driver_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataShippingTrackingInfo
     */
    'driver_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataShippingTrackingInfo
     */
    'ctime'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataShippingTrackingInfo
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataShippingTrackingInfo
     */
    'type'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataStatus
 */
export interface GetOrderListResponseDataStatus {
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof GetOrderListResponseDataStatus
     */
    'status_label'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {GetOrderListResponseDataStatusHeaderText}
     * @memberof GetOrderListResponseDataStatus
     */
    'header_text'?: GetOrderListResponseDataStatusHeaderText;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataStatus
     */
    'header_image'?: string;
    /**
     * 
     * @type {GetOrderListResponseDataStatusHeaderText}
     * @memberof GetOrderListResponseDataStatus
     */
    'popup_msg'?: GetOrderListResponseDataStatusHeaderText;
    /**
     * 
     * @type {GetOrderListResponseDataStatusHeaderText}
     * @memberof GetOrderListResponseDataStatus
     */
    'list_view_text'?: GetOrderListResponseDataStatusHeaderText;
    /**
     * 
     * @type {GetOrderListResponseDataStatusHeaderText}
     * @memberof GetOrderListResponseDataStatus
     */
    'list_view_sub_text'?: GetOrderListResponseDataStatusHeaderText;
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof GetOrderListResponseDataStatus
     */
    'list_view_status_label'?: GetOrderListResponseDataStatusStatusLabel;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataStatusHeaderText
 */
export interface GetOrderListResponseDataStatusHeaderText {
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataStatusHeaderText
     */
    'text'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataStatusHeaderText
     */
    'tl'?: boolean;
    /**
     * 
     * @type {Array<GetOrderListResponseDataStatusHeaderTextAttributes>}
     * @memberof GetOrderListResponseDataStatusHeaderText
     */
    'attributes'?: Array<GetOrderListResponseDataStatusHeaderTextAttributes>;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataStatusHeaderTextAttributes
 */
export interface GetOrderListResponseDataStatusHeaderTextAttributes {
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataStatusHeaderTextAttributes
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataStatusHeaderTextAttributes
     */
    'value'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetOrderListResponseDataStatusHeaderTextAttributes
     */
    'type'?: number;
}
/**
 * 
 * @export
 * @interface GetOrderListResponseDataStatusStatusLabel
 */
export interface GetOrderListResponseDataStatusStatusLabel {
    /**
     * 
     * @type {string}
     * @memberof GetOrderListResponseDataStatusStatusLabel
     */
    'text'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderListResponseDataStatusStatusLabel
     */
    'tl'?: boolean;
}
/**
 * 
 * @export
 * @interface GetWalletOverviewRequest
 */
export interface GetWalletOverviewRequest {
    /**
     * 
     * @type {UserV2WalletOverviewMeta}
     * @memberof GetWalletOverviewRequest
     */
    'meta': UserV2WalletOverviewMeta;
    /**
     * 
     * @type {object}
     * @memberof GetWalletOverviewRequest
     */
    'data'?: object;
}
/**
 * 
 * @export
 * @interface GetWalletOverviewResponse
 */
export interface GetWalletOverviewResponse {
    /**
     * 
     * @type {number}
     * @memberof GetWalletOverviewResponse
     */
    'code'?: number;
    /**
     * 
     * @type {GetWalletOverviewResponseData}
     * @memberof GetWalletOverviewResponse
     */
    'data'?: GetWalletOverviewResponseData;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponse
     */
    'msg'?: string;
}
/**
 * 
 * @export
 * @interface GetWalletOverviewResponseData
 */
export interface GetWalletOverviewResponseData {
    /**
     * 
     * @type {Array<object>}
     * @memberof GetWalletOverviewResponseData
     */
    'pending_guide_processes'?: Array<object>;
    /**
     * 
     * @type {GetWalletOverviewResponseDataBuyerWallet}
     * @memberof GetWalletOverviewResponseData
     */
    'buyer_wallet'?: GetWalletOverviewResponseDataBuyerWallet;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseData
     */
    'coin_amount'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetWalletOverviewResponseData
     */
    'screen_lock_status'?: number;
}
/**
 * 
 * @export
 * @interface GetWalletOverviewResponseDataBuyerWallet
 */
export interface GetWalletOverviewResponseDataBuyerWallet {
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'user_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'user_status'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'wallet_provider'?: number;
    /**
     * 
     * @type {GetWalletOverviewResponseDataBuyerWalletWalletBalance}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'wallet_balance'?: GetWalletOverviewResponseDataBuyerWalletWalletBalance;
    /**
     * 
     * @type {boolean}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'hide_refund_wallet'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'hide_cashback_wallet'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'hide_special_cashback_wallet'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetWalletOverviewResponseDataBuyerWallet
     */
    'is_merchant'?: boolean;
}
/**
 * 
 * @export
 * @interface GetWalletOverviewResponseDataBuyerWalletWalletBalance
 */
export interface GetWalletOverviewResponseDataBuyerWalletWalletBalance {
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'cashback'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'incoming'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'main'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'non_transferable_balance'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'outgoing'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'pending'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'refund'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'special_cashback'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'total'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWalletOverviewResponseDataBuyerWalletWalletBalance
     */
    'transferable_balance'?: string;
}
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {InlineResponse200Data}
     * @memberof InlineResponse200
     */
    'data'?: InlineResponse200Data;
}
/**
 * 
 * @export
 * @interface InlineResponse200Data
 */
export interface InlineResponse200Data {
    /**
     * 
     * @type {GetOrderListResponseDataStatus}
     * @memberof InlineResponse200Data
     */
    'status'?: GetOrderListResponseDataStatus;
    /**
     * 
     * @type {InlineResponse200DataPcShipping}
     * @memberof InlineResponse200Data
     */
    'pc_shipping'?: InlineResponse200DataPcShipping;
    /**
     * 
     * @type {InlineResponse200DataAddress}
     * @memberof InlineResponse200Data
     */
    'address'?: InlineResponse200DataAddress;
    /**
     * 
     * @type {GetOrderListResponseDataGuarantee}
     * @memberof InlineResponse200Data
     */
    'guarantee'?: GetOrderListResponseDataGuarantee;
    /**
     * 
     * @type {InlineResponse200DataInfoCard}
     * @memberof InlineResponse200Data
     */
    'info_card'?: InlineResponse200DataInfoCard;
    /**
     * 
     * @type {InlineResponse200DataInvoice}
     * @memberof InlineResponse200Data
     */
    'invoice'?: InlineResponse200DataInvoice;
    /**
     * 
     * @type {InlineResponse200DataPaymentMethod}
     * @memberof InlineResponse200Data
     */
    'payment_method'?: InlineResponse200DataPaymentMethod;
    /**
     * 
     * @type {InlineResponse200DataCoins}
     * @memberof InlineResponse200Data
     */
    'coins'?: InlineResponse200DataCoins;
    /**
     * 
     * @type {InlineResponse200DataPcProcessingInfo}
     * @memberof InlineResponse200Data
     */
    'pc_processing_info'?: InlineResponse200DataPcProcessingInfo;
    /**
     * 
     * @type {Array<GetOrderListResponseDataPrimaryButtons>}
     * @memberof InlineResponse200Data
     */
    'secondary_buttons'?: Array<GetOrderListResponseDataPrimaryButtons>;
    /**
     * 
     * @type {Array<GetOrderListResponseDataPrimaryButtons>}
     * @memberof InlineResponse200Data
     */
    'primary_buttons'?: Array<GetOrderListResponseDataPrimaryButtons>;
    /**
     * 
     * @type {Array<number>}
     * @memberof InlineResponse200Data
     */
    'components'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200Data
     */
    'list_type'?: number;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataAddress
 */
export interface InlineResponse200DataAddress {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataAddress
     */
    'shipping_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataAddress
     */
    'shipping_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataAddress
     */
    'shipping_address'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataAddress
     */
    'is_buyer_address_editable'?: boolean;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataCoins
 */
export interface InlineResponse200DataCoins {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataCoins
     */
    'coin_earn'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataCoins
     */
    'coin_basic_earn'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataCoins
     */
    'coin_earn_by_shopee_voucher'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataCoins
     */
    'redirect_to_coin_page'?: boolean;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCard
 */
export interface InlineResponse200DataInfoCard {
    /**
     * 
     * @type {Array<InlineResponse200DataInfoCardParcelCards>}
     * @memberof InlineResponse200DataInfoCard
     */
    'parcel_cards'?: Array<InlineResponse200DataInfoCardParcelCards>;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataInfoCard
     */
    'is_multi_parcel'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCard
     */
    'subtotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCard
     */
    'final_total'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCard
     */
    'vat_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCard
     */
    'amount_paid'?: number;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCardExtraInfo
 */
export interface InlineResponse200DataInfoCardExtraInfo {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataInfoCardExtraInfo
     */
    'is_shipment_grouped'?: boolean;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCardParcelCards
 */
export interface InlineResponse200DataInfoCardParcelCards {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCardParcelCards
     */
    'parcel_no'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataInfoCardParcelCards
     */
    'forder_id'?: string;
    /**
     * 
     * @type {InlineResponse200DataInfoCardParcelStatusInfo}
     * @memberof InlineResponse200DataInfoCardParcelCards
     */
    'parcel_status_info'?: InlineResponse200DataInfoCardParcelStatusInfo;
    /**
     * 
     * @type {GetOrderListResponseDataInfoCardShopInfo}
     * @memberof InlineResponse200DataInfoCardParcelCards
     */
    'shop_info'?: GetOrderListResponseDataInfoCardShopInfo;
    /**
     * 
     * @type {GetOrderListResponseDataInfoCardProductInfo}
     * @memberof InlineResponse200DataInfoCardParcelCards
     */
    'product_info'?: GetOrderListResponseDataInfoCardProductInfo;
    /**
     * 
     * @type {InlineResponse200DataInfoCardPaymentInfo}
     * @memberof InlineResponse200DataInfoCardParcelCards
     */
    'payment_info'?: InlineResponse200DataInfoCardPaymentInfo;
    /**
     * 
     * @type {InlineResponse200DataInfoCardExtraInfo}
     * @memberof InlineResponse200DataInfoCardParcelCards
     */
    'extra_info'?: InlineResponse200DataInfoCardExtraInfo;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCardParcelStatusInfo
 */
export interface InlineResponse200DataInfoCardParcelStatusInfo {
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataInfoCardParcelStatusInfo
     */
    'label'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataInfoCardParcelStatusInfo
     */
    'tooltip'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCardParcelStatusInfo
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCardPaymentInfo
 */
export interface InlineResponse200DataInfoCardPaymentInfo {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataInfoCardPaymentInfo
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCardPaymentInfo
     */
    'total_price'?: number;
    /**
     * 
     * @type {Array<InlineResponse200DataInfoCardPaymentInfoInfoRows>}
     * @memberof InlineResponse200DataInfoCardPaymentInfo
     */
    'info_rows'?: Array<InlineResponse200DataInfoCardPaymentInfoInfoRows>;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCardPaymentInfoInfoRows
 */
export interface InlineResponse200DataInfoCardPaymentInfoInfoRows {
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataInfoCardPaymentInfoInfoRows
     */
    'info_label'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {InlineResponse200DataInfoCardPaymentInfoInfoValue}
     * @memberof InlineResponse200DataInfoCardPaymentInfoInfoRows
     */
    'info_value'?: InlineResponse200DataInfoCardPaymentInfoInfoValue;
    /**
     * 
     * @type {InlineResponse200DataInfoCardPaymentInfoInfoTooltip}
     * @memberof InlineResponse200DataInfoCardPaymentInfoInfoRows
     */
    'info_tooltip'?: InlineResponse200DataInfoCardPaymentInfoInfoTooltip;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCardPaymentInfoInfoTooltip
 */
export interface InlineResponse200DataInfoCardPaymentInfoInfoTooltip {
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataInfoCardPaymentInfoInfoTooltip
     */
    'tooltip'?: GetOrderListResponseDataStatusStatusLabel;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInfoCardPaymentInfoInfoValue
 */
export interface InlineResponse200DataInfoCardPaymentInfoInfoValue {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataInfoCardPaymentInfoInfoValue
     */
    'value'?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInfoCardPaymentInfoInfoValue
     */
    'type'?: number;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataInvoice
 */
export interface InlineResponse200DataInvoice {
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataInvoice
     */
    'display_invoice'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataInvoice
     */
    'shop_id'?: number;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataPaymentMethod
 */
export interface InlineResponse200DataPaymentMethod {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPaymentMethod
     */
    'payment_method'?: number;
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataPaymentMethod
     */
    'payment_channel_name'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataPaymentMethod
     */
    'can_change_payment_method'?: boolean;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataPcProcessingInfo
 */
export interface InlineResponse200DataPcProcessingInfo {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'create_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'shipping_confirm_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'pay_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'cancel_reason'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'delivery_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'complete_time'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'is_rated'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'rate_to_seller_by_date'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'order_payment_method'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'order_request_type'?: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'paid_amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcProcessingInfo
     */
    'order_sn'?: string;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataPcShipping
 */
export interface InlineResponse200DataPcShipping {
    /**
     * 
     * @type {Array<InlineResponse200DataPcShippingForderShippingInfoList>}
     * @memberof InlineResponse200DataPcShipping
     */
    'forder_shipping_info_list'?: Array<InlineResponse200DataPcShippingForderShippingInfoList>;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataPcShipping
     */
    'is_multi_parcel'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcShipping
     */
    'num_parcels'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataPcShipping
     */
    'can_modify_fulfilment_channel'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcShipping
     */
    'fulfilment_carrier_channel_id'?: number;
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataPcShipping
     */
    'masked_carrier'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataPcShipping
     */
    'fulfilment_carrier'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShipping
     */
    'disable_edit_fulfilment_channel_reason'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataPcShipping
     */
    'use_standard_proof'?: boolean;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataPcShippingForderShippingInfoList
 */
export interface InlineResponse200DataPcShippingForderShippingInfoList {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcShippingForderShippingInfoList
     */
    'parcel_no'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingForderShippingInfoList
     */
    'tracking_number'?: string;
    /**
     * 
     * @type {Array<InlineResponse200DataPcShippingTrackingInfoList>}
     * @memberof InlineResponse200DataPcShippingForderShippingInfoList
     */
    'tracking_info_list'?: Array<InlineResponse200DataPcShippingTrackingInfoList>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcShippingForderShippingInfoList
     */
    'fulfilment_carrier_channel_id'?: number;
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataPcShippingForderShippingInfoList
     */
    'masked_carrier'?: GetOrderListResponseDataStatusStatusLabel;
    /**
     * 
     * @type {GetOrderListResponseDataStatusStatusLabel}
     * @memberof InlineResponse200DataPcShippingForderShippingInfoList
     */
    'fulfilment_carrier'?: GetOrderListResponseDataStatusStatusLabel;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataPcShippingMilestone
 */
export interface InlineResponse200DataPcShippingMilestone {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingMilestone
     */
    'image_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingMilestone
     */
    'text'?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcShippingMilestone
     */
    'color'?: number;
}
/**
 * 
 * @export
 * @interface InlineResponse200DataPcShippingTrackingInfoList
 */
export interface InlineResponse200DataPcShippingTrackingInfoList {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'driver_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'driver_name'?: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'ctime'?: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'license_plate_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'receiver_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'pin_code'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'have_std_epod'?: boolean;
    /**
     * 
     * @type {InlineResponse200DataPcShippingMilestone}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'milestone'?: InlineResponse200DataPcShippingMilestone;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200DataPcShippingTrackingInfoList
     */
    'epod'?: string;
}
/**
 * 
 * @export
 * @interface UserV2WalletOverviewMeta
 */
export interface UserV2WalletOverviewMeta {
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'sdk_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'latitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'app_package_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'device_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'os_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'app_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'sz_blackbox'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'rn_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'device_model'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'longitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'source': string;
    /**
     * 
     * @type {number}
     * @memberof UserV2WalletOverviewMeta
     */
    'os': number;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'device_brand'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'device_id': string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'arch'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserV2WalletOverviewMeta
     */
    'network_type'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'device_fingerprint'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'black_box'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'device_ip'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserV2WalletOverviewMeta
     */
    'is_jailbreak'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserV2WalletOverviewMeta
     */
    'language'?: string;
}

/**
 * ShopeeMallApi - axios parameter creator
 * @export
 */
export const ShopeeMallApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get order detail
         * @param {number} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderDetail: async (orderId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('getOrderDetail', 'orderId', orderId)
            const localVarPath = `/api/v4/order/get_order_detail`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (orderId !== undefined) {
                localVarQueryParameter['order_id'] = orderId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get order list
         * @param {number} [limit] 
         * @param {number} [listType] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderList: async (limit?: number, listType?: number, offset?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v4/order/get_order_list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (listType !== undefined) {
                localVarQueryParameter['list_type'] = listType;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShopeeMallApi - functional programming interface
 * @export
 */
export const ShopeeMallApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ShopeeMallApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get order detail
         * @param {number} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrderDetail(orderId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrderDetail(orderId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get order list
         * @param {number} [limit] 
         * @param {number} [listType] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrderList(limit?: number, listType?: number, offset?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetOrderListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrderList(limit, listType, offset, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ShopeeMallApi - factory interface
 * @export
 */
export const ShopeeMallApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ShopeeMallApiFp(configuration)
    return {
        /**
         * 
         * @summary Get order detail
         * @param {number} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderDetail(orderId: number, options?: any): AxiosPromise<InlineResponse200> {
            return localVarFp.getOrderDetail(orderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get order list
         * @param {number} [limit] 
         * @param {number} [listType] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrderList(limit?: number, listType?: number, offset?: number, options?: any): AxiosPromise<GetOrderListResponse> {
            return localVarFp.getOrderList(limit, listType, offset, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getOrderDetail operation in ShopeeMallApi.
 * @export
 * @interface ShopeeMallApiGetOrderDetailRequest
 */
export interface ShopeeMallApiGetOrderDetailRequest {
    /**
     * 
     * @type {number}
     * @memberof ShopeeMallApiGetOrderDetail
     */
    readonly orderId: number
}

/**
 * Request parameters for getOrderList operation in ShopeeMallApi.
 * @export
 * @interface ShopeeMallApiGetOrderListRequest
 */
export interface ShopeeMallApiGetOrderListRequest {
    /**
     * 
     * @type {number}
     * @memberof ShopeeMallApiGetOrderList
     */
    readonly limit?: number

    /**
     * 
     * @type {number}
     * @memberof ShopeeMallApiGetOrderList
     */
    readonly listType?: number

    /**
     * 
     * @type {number}
     * @memberof ShopeeMallApiGetOrderList
     */
    readonly offset?: number
}

/**
 * ShopeeMallApi - object-oriented interface
 * @export
 * @class ShopeeMallApi
 * @extends {BaseAPI}
 */
export class ShopeeMallApi extends BaseAPI {
    /**
     * 
     * @summary Get order detail
     * @param {ShopeeMallApiGetOrderDetailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShopeeMallApi
     */
    public getOrderDetail(requestParameters: ShopeeMallApiGetOrderDetailRequest, options?: AxiosRequestConfig) {
        return ShopeeMallApiFp(this.configuration).getOrderDetail(requestParameters.orderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get order list
     * @param {ShopeeMallApiGetOrderListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShopeeMallApi
     */
    public getOrderList(requestParameters: ShopeeMallApiGetOrderListRequest = {}, options?: AxiosRequestConfig) {
        return ShopeeMallApiFp(this.configuration).getOrderList(requestParameters.limit, requestParameters.listType, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * ShopeePayApi - axios parameter creator
 * @export
 */
export const ShopeePayApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get wallet overview
         * @param {GetWalletOverviewRequest} [getWalletOverviewRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWalletOverview: async (getWalletOverviewRequest?: GetWalletOverviewRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/v2/wallet-overview`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication xToken required
            await setApiKeyToObject(localVarHeaderParameter, "x-token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getWalletOverviewRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShopeePayApi - functional programming interface
 * @export
 */
export const ShopeePayApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ShopeePayApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get wallet overview
         * @param {GetWalletOverviewRequest} [getWalletOverviewRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWalletOverview(getWalletOverviewRequest?: GetWalletOverviewRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetWalletOverviewResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWalletOverview(getWalletOverviewRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ShopeePayApi - factory interface
 * @export
 */
export const ShopeePayApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ShopeePayApiFp(configuration)
    return {
        /**
         * 
         * @summary Get wallet overview
         * @param {GetWalletOverviewRequest} [getWalletOverviewRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWalletOverview(getWalletOverviewRequest?: GetWalletOverviewRequest, options?: any): AxiosPromise<GetWalletOverviewResponse> {
            return localVarFp.getWalletOverview(getWalletOverviewRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getWalletOverview operation in ShopeePayApi.
 * @export
 * @interface ShopeePayApiGetWalletOverviewRequest
 */
export interface ShopeePayApiGetWalletOverviewRequest {
    /**
     * 
     * @type {GetWalletOverviewRequest}
     * @memberof ShopeePayApiGetWalletOverview
     */
    readonly getWalletOverviewRequest?: GetWalletOverviewRequest
}

/**
 * ShopeePayApi - object-oriented interface
 * @export
 * @class ShopeePayApi
 * @extends {BaseAPI}
 */
export class ShopeePayApi extends BaseAPI {
    /**
     * 
     * @summary Get wallet overview
     * @param {ShopeePayApiGetWalletOverviewRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShopeePayApi
     */
    public getWalletOverview(requestParameters: ShopeePayApiGetWalletOverviewRequest = {}, options?: AxiosRequestConfig) {
        return ShopeePayApiFp(this.configuration).getWalletOverview(requestParameters.getWalletOverviewRequest, options).then((request) => request(this.axios, this.basePath));
    }
}


